spring:
  profiles:
    active:
      - dev
---
server:
  port: 7030
spring:
  profiles: dev
  application:
    name: configServer
  cloud:
    config:
      server:
        git:
          uri: git@github.com:yanjun-sui/test-config.git
---
server:
  port: 7040
spring:
  profiles: run
  application:
    name: configServer-run
---
server:
  port: 7050
spring:
  profiles: test
  application:
    name: configServer-test

	server:
  port: 8080
spring:
  profiles: dev
  application:
    name: dept-consumer
eureka:
  instance:
    instance-id: consumer-8080
    prefer-ip-address: true
    hostname: localhost
  client:
    service-url:
      defaultZone: http://127.0.0.1:7011/eureka,http://127.0.0.1:7012/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"
info:
  name: consumer